<?php
	defined('BASEPATH') OR exit('No direct script access allowed');
	$config['base_url'] = 'http://localhost:8000';
	//$config['base_url'] = 'http://localhost/Barun';
	$config['index_page'] = '';
	$config['uri_protocol'] = 'REQUEST_URI';
	$config['url_suffix'] = '';
	$config['language'] = 'english';
	$config['charset'] = 'UTF-8';
	$config['enable_hooks'] = TRUE;
	$config['subclass_prefix'] = 'MY_';
	$config['composer_autoload'] = FALSE;
	$config['permitted_uri_chars'] = 'a-z 0-9~%.:_\-';
	$config['allow_get_array'] = TRUE;
	$config['enable_query_strings'] = FALSE;
	$config['controller_trigger'] = 'c';
	$config['function_trigger'] = 'm';
	$config['directory_trigger'] = 'd';
	$config['log_threshold'] = 0;
	$config['log_path'] = '';
	$config['log_file_extension'] = '';
	$config['log_file_permissions'] = 0644;
	$config['log_date_format'] = 'Y-m-d H:i:s';
	$config['error_views_path'] = '';
	$config['cache_path'] = '';
	$config['cache_query_string'] = FALSE;
	$config['encryption_key'] = 'rLmO2GTQjsFAhtWXoE3KV68xlqagJbPSc1Yze';
	$config['sess_driver'] = 'database';
	$config['sess_cookie_name'] = 'sess';
	$config['sess_expiration'] = 7200;
	$config['sess_save_path'] = 'sessions';
	$config['sess_match_ip'] = FALSE;
	$config['sess_time_to_update'] = 300;
	$config['sess_regenerate_destroy'] = FALSE;
	$config['cookie_prefix']    = 'sma_';
	$config['cookie_domain']    = '';
	$config['cookie_path']      = '/';

	// $config['cookie_secure']    = true;
	$config['cookie_secure']    = FALSE;
	$config['cookie_httponly']  = FALSE;
	$config['standardize_newlines'] = FALSE;
	$config['global_xss_filtering'] = TRUE;

	// $config['csrf_protection'] = TRUE;
	$config['csrf_protection'] = FALSE;
	$config['csrf_token_name'] = 'token';
	$config['csrf_cookie_name'] = 'token_cookie';
	$config['csrf_expire'] = 7200;
	$config['csrf_regenerate'] = FALSE;
	$config['csrf_exclude_uris'] = array('payments/paypalipn', 'payments/skrillipn', 'welcome/image_upload','api/post_carts','api/update_payment_carts',"apiapp/.*+");
	$config['compress_output'] = FALSE;
	$config['time_reference'] = 'local';
	$config['rewrite_short_tags'] = TRUE;
	$config['proxy_ips'] = '';
	define('FIREBASE_API_KEY', 'AAAAs6qgwnQ:APA91bGMc7AE0P92R_bvZ38MT6SpJWZRXvjGoR97yxCI5RlCYF9syKJuzEYaprcgHimGKdjh1RtwNj6EgKYoq_Y6fg8QNvZx_ykGuiB6kAErSLoET6iVtIZfVtvD2zId-y1jypZEwm3d');
	define('SITE_TMDT_URL', 'cn.alphasoftware.vn');
